# Generated by Django 4.0.4 on 2022-06-23 18:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('scale', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_description', models.TextField(blank=True, default=None, max_length=180, null=True)),
                ('blossom', models.CharField(max_length=180)),
                ('fruit', models.CharField(max_length=180)),
                ('climate', models.CharField(max_length=180)),
                ('pick_maturity', models.CharField(max_length=180)),
                ('usage', models.CharField(max_length=250)),
                ('bio', models.BooleanField(default=False)),
                ('pollinator', models.CharField(max_length=250)),
                ('properties', models.CharField(max_length=250)),
                ('output', models.CharField(max_length=250)),
                ('disease_possibility', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('planted_on', models.DateTimeField(default=datetime.datetime.now)),
                ('organic', models.BooleanField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('cut', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trees', to=settings.AUTH_USER_MODEL)),
                ('variety', models.ForeignKey(on_delete=models.SET(999999), to='api.variety')),
            ],
            options={
                'ordering': ('row', 'column'),
            },
        ),
        migrations.CreateModel(
            name='OrchardMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('image_photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image_description', models.TextField(blank=True, default=None, max_length=180, null=True)),
                ('frostSensitivity', models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('veryHigh', 'veryHigh')], max_length=30, null=True)),
                ('growthHabit', models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('veryHigh', 'veryHigh')], max_length=30, null=True)),
                ('yieldHabit', models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('veryHigh', 'veryHigh')], max_length=30, null=True)),
                ('temperature', models.CharField(blank=True, choices=[('cold', 'cold'), ('medium', 'medium'), ('warm', 'warm')], max_length=30, null=True)),
                ('precipitation', models.CharField(blank=True, choices=[('dry', 'dry'), ('normal', 'normal'), ('wet', 'wet')], max_length=30, null=True)),
                ('lateFrost', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tree')),
            ],
        ),
        migrations.CreateModel(
            name='LabMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('strengthMeasurement', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('flavorMeasurement', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True)),
                ('acidMeasurement', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sugarMeasurement', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tree')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disease')),
                ('orchardMeasurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orchardmeasurement')),
            ],
        ),
    ]
