# Generated by Django 4.0.4 on 2022-06-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='owner',
        ),
    ]
