# Generated by Django 4.0.4 on 2022-05-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orchardmeasurement',
            old_name='FrostSensitivity',
            new_name='frostSensitivity',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tree',
        ),
        migrations.AddField(
            model_name='image',
            name='variety',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.variety'),
        ),
    ]
