# Generated by Django 4.0.4 on 2022-05-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_acidmeasurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acidmeasurement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='variety_id',
            new_name='variety',
        ),
        migrations.AlterField(
            model_name='acidmeasurement',
            name='scale',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'B')], max_length=30),
        ),
    ]
