# Generated by Django 4.0.4 on 2022-06-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tree_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasemeasurement',
            name='value',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='cut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='organic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variety',
            name='pollinator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
