# Generated by Django 4.0.4 on 2022-06-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_diseasemeasurement_value_alter_tree_cut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='fruit',
        ),
    ]
