# Generated by Django 4.0.4 on 2022-05-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_image_url_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='photo',
        ),
    ]
