# Generated by Django 4.0.4 on 2022-05-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_image_orchardmeasurement_remove_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orchardmeasurement',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='variety',
            old_name='photo',
            new_name='image',
        ),
    ]
