# Generated by Django 4.0.4 on 2022-05-19 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_photo_orchardmeasurement_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='image',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.image'),
        ),
    ]
