# Generated by Django 4.0.4 on 2022-05-19 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_variety_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
    ]
