# Generated by Django 4.0.4 on 2022-06-13 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_variety_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
    ]
