# Generated by Django 4.0.4 on 2022-06-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_variety_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='image',
        ),
        migrations.AddField(
            model_name='variety',
            name='image_description',
            field=models.TextField(default='TEstDescriptionBild'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variety',
            name='image_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
