# Generated by Django 4.0.4 on 2022-06-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_variety_image_variety_image_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='image_description',
        ),
    ]
