# Generated by Django 4.0.4 on 2022-06-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_orchardmeasurement_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmeasurement',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orchardmeasurement',
            name='precipitation',
            field=models.CharField(blank=True, choices=[('Trocken', 'Trocken'), ('Normal', 'Normal'), ('Feucht', 'Feucht')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orchardmeasurement',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='labmeasurement',
            name='acidMeasurement',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='labmeasurement',
            name='flavorMeasurement',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='labmeasurement',
            name='strengthMeasurement',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='labmeasurement',
            name='sugarMeasurement',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='orchardmeasurement',
            name='frostSensitivity',
            field=models.CharField(blank=True, choices=[('Viel', 'Viel'), ('Mittel', 'Mittel'), ('Wenig', 'Wenig')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orchardmeasurement',
            name='growthHabit',
            field=models.CharField(blank=True, choices=[('Viel', 'Viel'), ('Mittel', 'Mittel'), ('Wenig', 'Wenig')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orchardmeasurement',
            name='season',
            field=models.CharField(blank=True, choices=[('Frühling', 'Frühling'), ('Sommer', 'Sommer'), ('Herbst', 'Herbst'), ('Winter', 'Winter')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orchardmeasurement',
            name='temperature',
            field=models.CharField(blank=True, choices=[('Viel', 'Viel'), ('Mittel', 'Mittel'), ('Wenig', 'Wenig')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orchardmeasurement',
            name='yieldHabit',
            field=models.CharField(blank=True, choices=[('Viel', 'Viel'), ('Mittel', 'Mittel'), ('Wenig', 'Wenig')], max_length=30, null=True),
        ),
    ]
