# Generated by Django 4.0.4 on 2022-06-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_orchardmeasurement_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orchardmeasurement',
            name='frostSensitivity',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('veryHigh', 'veryHigh')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orchardmeasurement',
            name='growthHabit',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('veryHigh', 'veryHigh')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orchardmeasurement',
            name='precipitation',
            field=models.CharField(blank=True, choices=[('dry', 'dry'), ('normal', 'normal'), ('wet', 'wet')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orchardmeasurement',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'spring'), ('summer', 'summer'), ('fall', 'fall'), ('winter', 'winter')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orchardmeasurement',
            name='temperature',
            field=models.CharField(blank=True, choices=[('cold', 'cold'), ('medium', 'medium'), ('warm', 'warm')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orchardmeasurement',
            name='yieldHabit',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('veryHigh', 'veryHigh')], max_length=30, null=True),
        ),
    ]
