# Generated by Django 4.0.4 on 2022-06-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_orchardmeasurement_frostsensitivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orchardmeasurement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
